#!/usr/bin/env node
// -*- javascript -*-

var swf = process.argv[2]
var executable = "/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"

var child
var server = require("http").createServer(pass)

require("../bind-to-random-port.js")(server, function (port) {
  child = require("child_process").spawn(executable, [
    "file://" + encodeURI(require("path").resolve(swf)) + "?foo=" + port
  ])
})

setTimeout(fail, 10000)

function pass() {
  console.log("ok - " + swf + " without process")
  process.exit(0)
}

function fail() {
  console.log("not ok - " + swf + " without process")
  console.log("# timeout")
  process.exit(-1)
}

process.on("exit", function () {
  if (server) {
    server.close()
  }

  if (child) {
    child.kill("SIGKILL")
  }
})
